version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./dockercompose/mongo/:/data/db"
    ports:
      - "27017:27017"
    networks:
      - sa-network
  app:
    restart: on-failure
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - sa-network
    command: node index.js

networks:
  sa-network:
    name: sa-network